---
apiVersion: nfd.kubernetes.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: pt-nfd-config
  namespace: node-feature-discovery-operator
spec:
  instance: ""  ## instance is empty by default
  operand:
    image: registry.k8s.io/nfd/node-feature-discovery:v0.13.4
    imagePullPolicy: Always
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        labelSources: ["all"]
      sources:
        pci:
          deviceClassWhitelist:
            ## The PCI class, and (optional) subclass, e.g. "01" is also valid
            - "0100"
          deviceLabelFields:
            - "class"
            - "vendor"
            - "subsystem_vendor"
            - "subsystem_device"
