---
apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
spec:
  containers:
    - name: consumer
      image: quay.io/chrisp262/pt-consumer:latest
      securityContext:
        privileged: true
      resources:
        limits:
          example.com/ptemplate: 2
      volumeMounts:
        - mountPath: /hostdev
          name: host-dev
          readOnly: false
  volumes:
    - hostPath:
        path: /dev
      name: host-dev
