---
apiVersion: pt.example.com/v1alpha
kind: Ptemplate
metadata:
  name: consumer-pod
spec:
  maxdev: 5 
  defaultmsg: ptemplate
  consumer: quay.io/chrisp262/pt-device-plugin:consumer-latest
  requiredDevices: 2
  imagePullSecret:
    name: pt-char-pull-secret
  selector:
    node-role.kubernetes.io/worker: worker
