apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: ptemplate-char-dev-container
  name: ptemplate-char-dev-container
  namespace: ptemplate-demo
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ptemplate-char-dev-build
  name: ptemplate-char-dev-build
  namespace: ptemplate-demo
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    dockerfile: |
      ARG DTK
      FROM ${DTK} as builder
      ARG KVER
      RUN ls /lib/modules/
      WORKDIR /build/
      RUN git clone https://github.com/chr15p/partner_templates.git
      WORKDIR /build/partner_templates/src/kernel_module
      RUN make all install KVER=${KVER}
      FROM registry.redhat.io/ubi9/ubi-minimal
      ARG KVER
      # Required for installing `modprobe`
      RUN microdnf install -y kmod
      COPY --from=builder /lib/modules/${KVER}/ptemplate_char_dev.ko /lib/modules/${KVER}/
      COPY --from=builder /lib/modules/${KVER}/ptemplate_char_dev.ko /lib/modules/${KVER}/
      RUN depmod ${KVER}
  strategy:
    dockerStrategy:
      buildArgs:
        - name: KMODVER
          value: PTEMPLATE_DEMO
          # $ oc adm release info quay.io/openshift-release-dev/ocp-release:<cluster version>-x86_64 --image-for=driver-toolkit
        - name: DTK
          value: registry.redhat.io/openshift4/driver-toolkit-rhel9:v4.14
        - name: KVER
          value: 5.14.0-284.43.1.el9_2.x86_64
  output:
    to:
      kind: ImageStreamTag
      name: ptemplate-char-dev-container:demo
