apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: pt-char-dev
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ptemplate_char_dev
        dirName: /opt
        parameters:
          - max_dev=5
          - default_msg=ptemplate
      imagePullPolicy: Always
      kernelMappings:
        - regexp: '^.+$'
          containerImage: "quay.io/chrisp262/pt-char-dev:${KERNEL_FULL_VERSION}"
          build:
            dockerfileConfigMap:
              name: my-kmod-dockerfile
  imageRepoSecret:
    name: pt-char-pull-secret
  selector:
    node-role.kubernetes.io/worker: "worker"

apiVersion: v1
kind: ConfigMap
metadata:
  name: pt-char-dev-dockerfile
spec:
  data:
    Dockerfile: |
      FROM registry.redhat.io/openshift4/driver-toolkit-rhel9:v4.13.0-202308011445.p0.gd719bdc.assembly.stream as builder
      ARG KERNEL_VERSION
      WORKDIR /usr/src
      RUN ["git", "clone", "https://github.com/rh-ecosystem-edge/accelerator_templates.git"]
      WORKDIR /usr/src/partner_templates/kernel_module/
      RUN KERNEL_SRC_DIR=/lib/modules/${KERNEL_VERSION}/build make all KVER=${KERNEL_VERSION}

      FROM registry.redhat.io/ubi9/ubi-minimal
      ARG KERNEL_VERSION
      RUN ["microdnf", "install", "-y", "kmod"]
      COPY --from=builder /usr/src/partner_templates/kernel_module/*.ko /opt/lib/modules/$ {KERNEL_VERSION}/
      RUN depmod -b /opt ${KERNEL_VERSION}

      CMD [ "modprobe", "-d", "/opt", "ptemplate_char_dev"]
