---
apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: pt-char-pull-secret
data:
  .dockerconfigjson: <token with rw permissions on registry>

---
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: pt-char-dev
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: ptemplate_char_dev
        dirName: /opt  # Optional
        parameters:  # Optional
          - max_dev=5
          - default_msg=ptemplate
      imagePullPolicy: Always  # optional
      kernelMappings:  # At least one item is required
        - regexp: '^.+$'
          containerImage: "quay.io/chrisp262/pt-char-dev:${KERNEL_FULL_VERSION}-sb"
  imageRepoSecret:  # Optional. Used to pull ModuleLoader and device plugin images
    name: pt-char-pull-secret
  selector:
    node-role.kubernetes.io/worker: "worker"

