# permissions for end users to view ptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ptemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ptemplate-operator
    app.kubernetes.io/part-of: ptemplate-operator
    app.kubernetes.io/managed-by: kustomize
  name: ptemplate-viewer-role
rules:
- apiGroups:
  - pt.example.com
  resources:
  - ptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pt.example.com
  resources:
  - ptemplates/status
  verbs:
  - get
