# permissions for end users to edit ptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ptemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ptemplate-operator
    app.kubernetes.io/part-of: ptemplate-operator
    app.kubernetes.io/managed-by: kustomize
  name: ptemplate-editor-role
rules:
- apiGroups:
  - pt.example.com
  resources:
  - ptemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pt.example.com
  resources:
  - ptemplates/status
  verbs:
  - get
