name: spellcheck and lint docs
on:
  push:
     branches: [ master ]
  pull_request:
     branches: [ master ]

jobs:
  spellcheck-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: apt-get aspell yamllint
      - name: spellcehck markdown
        run: ${PWD}/tests/spellcheck.sh
      - name: Lint markdown files
        run: ${PWD}/tests/markdownlint.sh
      - name: Lint yaml files
        run: ${PWD}/tests/yamllint.sh
